### ISSUE TITLE
Boring as hellboi

### ISSUE THREAD

**Issue by thisbecasper** [JeppeK2017/jepify#1]
[Fix](https://www.google.com/search?q=boring&sxsrf=ACYBGNTXLP11hgU_yfx9WGuPbJYUghHZ6A:1580993599337&source=lnms&tbm=isch&sa=X&ved=2ahUKEwikroWP_LznAhVD26QKHX6OBK0Q_AUoAXoECA4QAw&biw=1440&bih=707#imgrc=3d1JuRs_AGWOPM) [nu](https://www.google.com/search?q=hellboi&sxsrf=ACYBGNTfCc2E6t67eA3vJW4wLa7ni3E9eA:1580993835065&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj5i7n__LznAhUSMewKHYNVCGYQ_AUoAXoECAwQAw&biw=1440&bih=658&dpr=2#imgrc=w8fgRmmjqgvhKM)

**Comment by JeppeK2017** [comment]
![okay](https://www.google.com/search?tbm=isch&sxsrf=ACYBGNQrjHzXrfpr6RiMfXbIjmQLKoniuw%3A1580993934203&source=hp&biw=1920&bih=991&ei=jg08XpjZCY31kwW9vIaACQ&q=ok&oq=ok&gs_l=img.3..0l10.2883.2935..3491...0.0..0.83.156.2......0....1..gws-wiz-img.CzAt-GykkMY&ved=0ahUKEwiY2Nmu_bznAhWN-qQKHT2eAZAQ4dUDCAU&uact=5#imgrc=ge5eQlUGoGcrzM

**Comment by Herbstein** [comment]
![laursen](https://avatars1.githubusercontent.com/u/36077970)

**Comment by jepify** [comment]
![](https://media-exp1.licdn.com/dms/image/C4D0BAQFY7LmgsevJhQ/company-logo_200_200/0?e=2159024400&v=beta&t=UbWhEBhQ4tktTSe2n3eaHLnpCGDX-JyHHitqx1vzLAE)
